[package]
name = "meio"
version = "0.50.0"
edition = "2018"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
repository = "https://github.com/rate-technology/meio"
homepage = "https://github.com/rate-technology/meio"
documentation = "https://docs.rs/meio/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["async", "actors"]
categories = ["concurrency"]
description = "A compact actors framework for the async epoch in Rust & Tokio"

[dependencies]
anyhow = "1.0.33"
async-trait = "0.1.41"
derive_more = "0.99.11"
futures = "0.3.6"
futures-delay-queue = { version = "0.4.2", optional = true}
futures-timer = { version = "3.0.2", optional = true }
log = "0.4.11"
thiserror = "1.0.22"
tokio = { version = "0.2.22", features = ["full"], optional = true }
uuid = { version = "0.8.1", features = ["v4"] }
wasm-bindgen-futures = { version = "0.4.19", optional = true }
wasm-timer = { version = "0.2.5", optional = true }

[dev-dependencies]
env_logger = "0.7.1"
hyper = "0.13.8"

[features]
server = ["tokio"]
client = [
    "wasm-bindgen-futures",
    "futures-timer/wasm-bindgen",
    "futures-delay-queue",
    "wasm-timer",
    "uuid/wasm-bindgen",
]
