[package]
name = "meio"
version = "0.65.0"
edition = "2018"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
repository = "https://github.com/rate-technology/meio"
homepage = "https://github.com/rate-technology/meio"
documentation = "https://docs.rs/meio/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["async", "actors"]
categories = ["concurrency"]
description = "A compact actors framework for the async epoch in Rust & Tokio"

[dependencies]
anyhow = "1.0.37"
async-trait = "0.1.42"
derive_more = "0.99.11"
futures = "0.3.9"
futures-timer = { version = "3.0.2", optional = true }
log = "0.4.11"
thiserror = "1.0.23"
tokio = { version = "1.0.1", features = ["full"], optional = true }
uuid = { version = "0.8.1", features = ["v4"] }
wasm-bindgen-futures = { version = "0.4.19", optional = true }

[dev-dependencies]
env_logger = "0.8.2"
hyper = "0.14.2"

[features]
default = ["tokio"]
wasm = [
    "wasm-bindgen-futures",
    "futures-timer/wasm-bindgen",
    "uuid/wasm-bindgen",
]
