[package]
name = "meio-connect"
version = "0.64.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rate-technology/meio"
homepage = "https://github.com/rate-technology/meio"
documentation = "https://docs.rs/meio-ws/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["async", "actors"]
categories = ["concurrency"]
description = "Set of connectors for MEIO framework"

[dependencies]
anyhow = "1.0.37"
async-trait = "0.1.42"
async-tungstenite = { version = "0.11.0", features = ["tokio-runtime"] }
derive_more = "0.99.11"
futures = "0.3.8"
headers = "0.3.2"
# TODO: And this when possible (
hyper = { version = "0.14.2", features = ["full"] }
log = "0.4.11"
meio = { version = "0.64.0", path = "../meio" }
meio-protocol = { version = "0.64.0", path = "../meio-protocol" }
serde = "1.0.118"
slab = "0.4.2"
thiserror = "1.0.23"
tokio = "1.0.1"
#tokio-tungstenite = "0.12.0"
tungstenite = "0.11.1"
