name: Release

on:
  release:
    types: [created]

jobs:
  rust-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Checking packages
        uses: katyo/publish-crates@v1
        with:
          dry-run: true

  rust-publish:
    runs-on: ubuntu-latest
    needs: rust-package
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Publishing crates
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_TOKEN }}
